apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-server-instance.fullname" . }}
  labels:

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ include "redis-server-instance.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
